/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName2 = string;
export type NoName3 = number;
export type NoName5 = string;
export type NoName6 = number;
export type NoName9 = number;
export type NoName10 = string;
export type NoName11 = number;
export type NoName12 = string;
export type NoName14 = number;
export type NoName15 = string;
export type NoName17 = number;
export type NoName18 = string;

export interface NoName {
  image: NoName1;
  video: NoName4;
  response: NoName7;
}
export interface NoName1 {
  dir: NoName2;
  limit: NoName3;
}
export interface NoName4 {
  dir: NoName5;
  limit: NoName6;
}
export interface NoName7 {
  success: NoName8;
  type: MIME;
  overwrite: NoName13;
  size: NoName16;
}
export interface NoName8 {
  code: NoName9;
  message: NoName10;
}
export interface MIME {
  code: NoName11;
  message: NoName12;
}
export interface NoName13 {
  code: NoName14;
  message: NoName15;
}
export interface NoName16 {
  code: NoName17;
  message: NoName18;
}
