/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HTTP = number;
export type StrictTransportSecurity = string;
export type ContentSecurityPolicyHTML = string;
export type ContentSecurityPolicyHTML1 = string;
export type Threshold = string;
export type NoName4 = string;
export type NoName5 = string[];
export type NoName6 = string[];
export type NoName9 = string;
export type NoName11 = string[];
export type NoName12 = string;
export type NoName10 = {
  paths: NoName11;
  value: NoName12;
}[];
export type NoName14 = string[];
export type NoName15 = string;
export type NoName13 = {
  extensions: NoName14;
  value: NoName15;
}[];
export type FilepathFor403Forbidden = string;
export type FilepathFor404NotFound = string;
export type NoName17 = string;
export type NoName19 = string;
export type Htpasswd = string;

export interface MediaW0SJp {
  port: HTTP;
  response: NoName;
  static: NoName3;
  errorpage: NoName16;
  logger: Logger;
  auth: NoName18;
}
export interface NoName {
  header: NoName1;
  compression: NoName2;
}
export interface NoName1 {
  hsts: StrictTransportSecurity;
  csp: ContentSecurityPolicyHTML;
  csp_html: ContentSecurityPolicyHTML1;
}
export interface NoName2 {
  threshold: Threshold;
}
export interface NoName3 {
  root: NoName4;
  extensions?: NoName5;
  indexes?: NoName6;
  headers: NoName7;
}
export interface NoName7 {
  mime: MIME;
  cache_control?: NoName8;
}
export interface MIME {
  path: MIME1;
  extension: MIME2;
}
export interface MIME1 {
  [k: string]: unknown;
}
export interface MIME2 {
  [k: string]: unknown;
}
export interface NoName8 {
  default: NoName9;
  path: NoName10;
  extension: NoName13;
}
export interface NoName16 {
  path_403: FilepathFor403Forbidden;
  path_404: FilepathFor404NotFound;
}
export interface Logger {
  path: NoName17;
}
export interface NoName18 {
  realm: NoName19;
  htpasswd_file: Htpasswd;
  json_401: JSON;
}
export interface JSON {
  [k: string]: unknown;
}
