/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = string;
export type NoName2 = string;
export type NoName4 = string[];
export type NoName5 = string[];

export interface NoName {
  orig_dir: NoName1;
  thumb_dir: NoName2;
  extension: NoName3;
  allow_origins: NoName4;
  referrer_exclusion_origins: NoName5;
}
export interface NoName3 {
  [k: string]: unknown;
}
