/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = string;
export type MIME1 = string;
export type NoName2 = string;
export type JPRGWebPAVIF = number;
export type CacheControl = string;
export type NoName3 = string[];
export type NoName4 = string[];

export interface NoName {
  thumb_dir: NoName1;
  type: MIME;
  quality_default: JPRGWebPAVIF;
  cache_control: CacheControl;
  allow_origins: NoName3;
  referrer_exclusion_origins: NoName4;
}
export interface MIME {
  [k: string]: {
    mime: MIME1;
    extension: NoName2;
  };
}
